### ISSUE TITLE
IOError during StageI training 

### ISSUE THREAD

**Issue by EruditeStranger** [hanzhanggit/StackGAN#18]
Here's the traceback for python run_exp.py --cfg cfg/birds.yml --gpu 0

Using config:
{'CONFIG_NAME': 'stageI',
 'DATASET_NAME': 'birds',
 'EMBEDDING_TYPE': 'cnn-rnn',
 'GAN': {'DF_DIM': 64,
         'EMBEDDING_DIM': 128,
         'GF_DIM': 128,
         'NETWORK_TYPE': 'default'},
 'GPU_ID': 0,
 'TEST': {'BATCH_SIZE': 64,
          'CAPTION_PATH': '',
          'HR_IMSIZE': 256,
          'LR_IMSIZE': 64,
          'NUM_COPY': 16,
          'PRETRAINED_MODEL': ''},
 'TRAIN': {'BATCH_SIZE': 64,
           'B_WRONG': True,
           'COEFF': {'KL': 2.0},
           'COND_AUGMENTATION': True,
           'DISCRIMINATOR_LR': 0.0002,
           'FINETUNE_LR': False,
           'FLAG': True,
           'FT_LR_RETIO': 0.1,
           'GENERATOR_LR': 0.0002,
           'LR_DECAY_EPOCH': 50,
           'MAX_EPOCH': 600,
           'NUM_COPY': 4,
           'NUM_EMBEDDING': 4,
           'PRETRAINED_EPOCH': 600,
           'PRETRAINED_MODEL': '',
           'SNAPSHOT_INTERVAL': 2000},
 'Z_DIM': 100}
Traceback (most recent call last):
  File "run_exp.py", line 47, in <module>
    dataset.test = dataset.get_data(filename_test)
  File "/home/rahul/StackGAN_Rahul/misc/datasets.py", line 223, in get_data
    with open(pickle_path + self.image_filename, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'Data/birds/test/76images.pickle'

Any idea about a step I may have missed?

**Comment by Periter** [comment]
em, you should run 'python ./misc/preprocess_birds.py' first, then it will create the pickle file.
