### ISSUE TITLE
module 'cunn' not found:No LuaRocks module found for cunn

### ISSUE THREAD

**Issue by Shubham-kale** [hanzhanggit/StackGAN#39]
**(tensorflow) oslab how_to_convert_text_to_images-master
$ sh demo/flowers_demo.sh**
/home/oslab/torch-cl/install/bin/luajit: /home/oslab/torch-cl/install/share/lua/5.1/trepl/init.lua:384: module 'cunn' not found:No LuaRocks module found for cunn
no field package.preload['cunn']
no file '/home/oslab/.luarocks/share/lua/5.1/cunn.lua'
no file '/home/oslab/.luarocks/share/lua/5.1/cunn/init.lua'
no file '/home/oslab/torch-cl/install/share/lua/5.1/cunn.lua'
no file '/home/oslab/torch-cl/install/share/lua/5.1/cunn/init.lua'
no file '/home/oslab/torch/install/share/lua/5.1/cunn.lua'
no file '/home/oslab/torch/install/share/lua/5.1/cunn/init.lua'
no file './cunn.lua'
no file '/home/oslab/torch/install/share/luajit-2.1.0-beta1/cunn.lua'
no file '/usr/local/share/lua/5.1/cunn.lua'
no file '/usr/local/share/lua/5.1/cunn/init.lua'
no file '/home/oslab/.luarocks/lib/lua/5.1/cunn.so'
no file '/home/oslab/torch-cl/install/lib/lua/5.1/cunn.so'
no file '/home/oslab/torch-cl/install/lib/cunn.so'
no file '/home/oslab/torch/install/lib/cunn.so'
no file '/home/oslab/torch/install/lib/lua/5.1/cunn.so'
no file './cunn.so'
no file '/usr/local/lib/lua/5.1/cunn.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
[C]: in function 'error'
/home/oslab/torch-cl/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
demo/get_embedding.lua:7: in main chunk
[C]: in function 'dofile'
...b/torch-cl/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
[C]: at 0x00405e90

**Comment by Shubham-kale** [comment]
**# I also ran the folowing command after that :-
$ luarocks install cunn**

_**then i am getting the following error log :-**_

Installing https://raw.githubusercontent.com/hughperkins/rocks-cl/master/cunn-scm-1.rockspec...
Using https://raw.githubusercontent.com/hughperkins/rocks-cl/master/cunn-scm-1.rockspec... switching to 'build' mode

Missing dependencies for cunn:
cutorch >= 1.0

Using https://raw.githubusercontent.com/hughperkins/rocks-cl/master/cutorch-scm-1.rockspec... switching to 'build' mode
Cloning into 'cutorch'...
remote: Counting objects: 105, done.
remote: Compressing objects: 100% (99/99), done.
remote: Total 105 (delta 8), reused 48 (delta 4), pack-reused 0
Receiving objects: 100% (105/105), 151.28 KiB | 348.00 KiB/s, done.
Resolving deltas: 100% (8/8), done.
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/oslab/torch-cl/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/oslab/torch-cl/install/lib/luarocks/rocks/cutorch/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install

-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/gcc-4.9
-- Check for working C compiler: /usr/bin/gcc-4.9 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-4.9
-- Check for working CXX compiler: /usr/bin/g++-4.9 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Torch7 in /home/oslab/torch-cl/install
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda (found suitable version "9.1", minimum required is "5.5")
-- Automatic GPU detection failed. Building for all known architectures.
-- Compiling for CUDA architecture: 2.0 2.1(2.0) 3.0 3.5 5.0 5.2
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_cutorch-scm-1-7825/cutorch/build
[ 17%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o
[ 17%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorTopK.cu.o
[ 17%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o
[ 17%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o
[ 17%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorCopy.cu.o
[ 20%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o
[ 17%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o
[ 17%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensor.cu.o
nvcc fatal : Unsupported gpu architecture 'compute_20'
nvcc fatal : Unsupported gpu architecture 'compute_20'
nvcc fatal : Unsupported gpu architecture 'compute_20'
nvcc fatal : Unsupported gpu architecture 'compute_20'
nvcc fatal : Unsupported gpu architecture 'compute_20'
nvcc fatal : Unsupported gpu architecture 'compute_20'
CMake Error at THC_generated_THCReduceApplyUtils.cu.o.cmake:207 (message):
Error generating
/tmp/luarocks_cutorch-scm-1-7825/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCReduceApplyUtils.cu.o

CMake Error at THC_generated_THCTensorTopK.cu.o.cmake:207 (message):
Error generating
/tmp/luarocks_cutorch-scm-1-7825/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorTopK.cu.o

CMake Error at THC_generated_THCStorageCopy.cu.o.cmake:207 (message):
Error generating
/tmp/luarocks_cutorch-scm-1-7825/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCStorageCopy.cu.o

CMake Error at THC_generated_THCTensor.cu.o.cmake:207 (message):
Error generating
/tmp/luarocks_cutorch-scm-1-7825/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensor.cu.o

CMake Error at THC_generated_THCBlas.cu.o.cmake:207 (message):
Error generating
/tmp/luarocks_cutorch-scm-1-7825/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCBlas.cu.o

lib/THC/CMakeFiles/THC.dir/build.make:63: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
lib/THC/CMakeFiles/THC.dir/build.make:224: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorTopK.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorTopK.cu.o] Error 1
lib/THC/CMakeFiles/THC.dir/build.make:91: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensor.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensor.cu.o] Error 1
lib/THC/CMakeFiles/THC.dir/build.make:84: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o] Error 1
CMake Error at THC_generated_THCStorage.cu.o.cmake:207 (message):
Error generating
/tmp/luarocks_cutorch-scm-1-7825/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCStorage.cu.o

lib/THC/CMakeFiles/THC.dir/build.make:70: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o] Error 1
lib/THC/CMakeFiles/THC.dir/build.make:77: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o] Error 1
nvcc fatal : Unsupported gpu architecture 'compute_20'
CMake Error at THC_generated_THCTensorCopy.cu.o.cmake:207 (message):
Error generating
/tmp/luarocks_cutorch-scm-1-7825/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorCopy.cu.o

lib/THC/CMakeFiles/THC.dir/build.make:98: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorCopy.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorCopy.cu.o] Error 1
nvcc fatal : Unsupported gpu architecture 'compute_20'
CMake Error at THC_generated_THCTensorMath.cu.o.cmake:207 (message):
Error generating
/tmp/luarocks_cutorch-scm-1-7825/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMath.cu.o

lib/THC/CMakeFiles/THC.dir/build.make:105: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o] Error 1
CMakeFiles/Makefile2:172: recipe for target 'lib/THC/CMakeFiles/THC.dir/all' failed
make[1]: *** [lib/THC/CMakeFiles/THC.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Error: Failed installing dependency: https://raw.githubusercontent.com/hughperkins/rocks-cl/master/cutorch-scm-1.rockspec - Build error: Failed building.

**Comment by Shubham-kale** [comment]
I ran 
$ nvcc -V
If not found install it by typing whatever it says in the description after running the above command
Then run the commands :-

$luarocks install cutorch
$luarocks install cunn

then the above error will not come

**Comment by ryanmccann1024** [comment]
Hi @Shubham-kale , I'm getting a timeout error from the above commands. More specifically:

```
atal: unable to connect to github.com:
github.com[0: 140.82.112.3]: errno=Connection timed out
```

I will post another comment if I have any luck with another solution.
