### ISSUE TITLE
 CUDA driver version is insufficient for CUDA runtime version 

### ISSUE THREAD

**Issue by Shubham-kale** [hanzhanggit/StackGAN#40]
The Error Log :- 

$ sh demo/birds_demo.sh
/home/oslab/torch-cl/install/bin/luajit: /home/oslab/torch-cl/install/share/lua/5.1/trepl/init.lua:384: /home/oslab/torch-cl/install/share/lua/5.1/trepl/init.lua:384: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /tmp/luarocks_cutorch-scm-1-5883/cutorch/lib/THC/THCGeneral.c:16
stack traceback:
	[C]: in function 'error'
	/home/oslab/torch-cl/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	demo/get_embedding.lua:7: in main chunk
	[C]: in function 'dofile'
	...b/torch-cl/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405e90

**Comment by nikhilkamat2** [comment]
Can't run the code without GPU that supports CUDA. 
If you have such a GPU, you have may issues in the installation of CUDA.
