### ISSUE TITLE
T7ReaderException: unknown object type / typeidx: 1936287828

### ISSUE THREAD

**Issue by Shubham-kale** [hanzhanggit/StackGAN#43]
The error log I am getting is :- 
T7ReaderException                         Traceback (most recent call last)
<ipython-input-14-2f8fcf38bceb> in <module>()
      6     cap_path ="/home/oslab/Data/flowers/example_captions"
      7 #torch.save(cap_path,'ascii')# ///// 'output.t7',
----> 8 t_file = torchfile.load(cap_path)
      9 
     10 captions_list = t_file.raw_txt

~/anaconda3/envs/tensorflow/lib/python3.6/site-packages/torchfile.py in load(filename, **kwargs)
    422     with open(filename, 'rb') as f:
    423         reader = T7Reader(f, **kwargs)
--> 424         return reader.read_obj()

~/anaconda3/envs/tensorflow/lib/python3.6/site-packages/torchfile.py in read_obj(self)
    412         else:
    413             raise T7ReaderException(
--> 414                 "unknown object type / typeidx: {}".format(typeidx))
    415 
    416 

T7ReaderException: unknown object type / typeidx: 1936287828

**Comment by Shubham-kale** [comment]
I think it is not able to get the example_captions.txt file in proper .t7 format

**Comment by Shubham-kale** [comment]
Problem is solved by saving the file with 
torch.save(caption_path)   function

**Comment by ASH1998** [comment]
Nice got it
