### ISSUE TITLE
Where to find example_captions.t7

### ISSUE THREAD

**Issue by brannondorsey** [hanzhanggit/StackGAN#6]
Hi I've followed the install instructions in the README, but I can't for the life of me figure out where to find `Data/flowers/example_captions.t7`? Same with birds. Are they simply the files like `lm_sje_nc4_cub_hybrid_gru18_a1_c512_ ... 70_1_10_trainvalids.txt_iter30000.t7` files that have been renamed?

**Comment by brannondorsey** [comment]
The specific error I get is trying to run `sh demo/flowers_demo.sh` after following all install instructions:
```
IOError: [Errno 2] No such file or directory: 'Data/flowers/example_captions.t7'
```

**Comment by brannondorsey** [comment]
Ah, it appears that this is the error that you get if you don't install torch. Installing torch with:

```
git clone https://github.com/torch/distro.git /root/torch --recursive
cd /root/torch
./install-deps && ./install.sh
```

fixed this problem for me.

**Comment by homaralex** [comment]
@brannondorsey what did you do afterwards? run the preprocessing script again?

**Comment by brannondorsey** [comment]
I'd try that, sure. Don't remember off hand but I know that once I installed torch running `demo/flowers_demo.sh` worked for me.

**Comment by EruditeStranger** [comment]
@brannondorsey I installed Torch as instructed [here](http://torch.ch/docs/getting-started.html#_), but I still couldn't get that script to run. Could it be due to installing LuaJIT or 5.2?

Here's the traceback:

```
 module 'image' not found:Failed loading module image in LuaRocks rock image 1.1.alpha-0
	no field package.preload['image']
	no file '/home/rahul/.luarocks/share/lua/5.1/image.lua'
	no file '/home/rahul/.luarocks/share/lua/5.1/image/init.lua'
	no file '/home/rahul/torch/install/share/lua/5.1/image.lua'
	no file '/home/rahul/torch/install/share/lua/5.1/image/init.lua'
	no file './image.lua'
	no file '/home/rahul/torch/install/share/luajit-2.1.0-beta1/image.lua'
	no file '/usr/local/share/lua/5.1/image.lua'
	no file '/usr/local/share/lua/5.1/image/init.lua'
	no file '/home/rahul/.luarocks/lib/lua/5.1/image.so'
	no file '/home/rahul/torch/install/lib/lua/5.1/image.so'
	no file '/home/rahul/torch/install/lib/image.so'
	no file './image.so'
	no file '/usr/local/lib/lua/5.1/image.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/home/rahul/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	demo/get_embedding.lua:4: in main chunk
	[C]: in function 'dofile'
	...ahul/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50
Traceback (most recent call last):
  File "demo/demo.py", line 175, in <module>
    t_file = torchfile.load(cap_path)
  File "/usr/local/lib/python2.7/dist-packages/torchfile.py", line 422, in load
    with open(filename, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'Data/flowers/example_captions.t7'
```

**Comment by brannondorsey** [comment]
I believe that installing torch prompts you to add something to your `~/.bashrc` that then allows you to call torch via `torch`. What happens if you run `torch`? Do you get command not found?

**Comment by brannondorsey** [comment]
I remember needing to run `source ~/.bashrc`  (or open a new terminal) after installing torch before that error went away.

**Comment by akshay-patade** [comment]
Still i am getting the same error

**Comment by HyperEntangledQubit** [comment]
Any solution I am getting this error on aws ec2 while in the torch environment

**Comment by akshay-patade** [comment]
I think it is because of the graphic card memory.It should be more than 2gb i think

**Comment by remyavijeesh22** [comment]
the torch is installed as per above instructions, but again
d for full details.
  yaml_cfg = edict(yaml.load(f))
Traceback (most recent call last):
  File "demo/demo.py", line 179, in <module>
    t_file = torchfile.load(cap_path)
  File "/home/hp/Gan_project_main/project/local/lib/python2.7/site-packages/torchfile.py", line 422, in load
    with open(filename, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'Data/flowers/example_captions.t7'
  this is produced, how can I solve this 
please reply as soon as possible 


thank you

**Comment by ast1997** [comment]
Even I can't see example_captions.t7 file

**Comment by ast1997** [comment]
![image](https://user-images.githubusercontent.com/60944614/74278104-460e1480-4cde-11ea-89be-e5aaffddd92e.png)
Can anyone help me with this error
